apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: org.lolibrary.web.library
    lolibrary.org/routing-name: org.lolibrary.web.library
  name: web-library
  namespace: lolibrary
  selfLink: /apis/extensions/v1beta1/namespaces/lolibrary/deployments/web-library
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: org.lolibrary.web.library
      lolibrary.org/routing-name: web.library
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      minUnavailable: 20%
  template:
    metadata:
      labels:
        app: org.lolibrary.web.library
        lolibrary.org/routing-name: web.library
      namespace: lolibrary
    spec:
      containers:
        - name: web-library
          image: PLACEHOLDER
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 150Mi
              cpu: 100m
            requests:
              memory: 20Mi
              cpu: 20m
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-library
  namespace: lolibrary
  labels:
    lolibrary.org/routing-name: web.library
  selfLink: /api/v1/namespaces/lolibrary/services/web-bizops
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: org.lolibrary.web.library
  sessionAffinity: None
  type: ClusterIP
